# See PEP 518 for the spec of this file
# https://www.python.org/dev/peps/pep-0518/

[tool.black]
line-length = 120
target_version = ['py310', 'py311']
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.pylint]
max-line-length = 120

[tool.mypy]
ignore_missing_imports = true

[tool.mypy.overrides]
module="*"
ignore_missing_imports = true
